//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDDC_6150
    {
        public int Level { get; set; }
        public string Class { get; set; }
        public int People { get; set; }
        public int PerShare { get; set; }
        public double CHEP { get; set; }
        public string StockNo { get; set; }
        public string StockName { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
    }
}
